const { mongoose } = require("mongoose");

const DiagnosisSchema = new mongoose.Schema({
    patientId: {type: String,unique: true,default: () => `PAT-${Math.floor(100000 + Math.random() * 900000)}`},
    username:{type: String, required: true, trim: true},
    phone:{type: String, required: true, validate: { validator: function(v) {return /^[6-9]\d{9}$/.test(v);},
        message: props => `${props.value} is not a valid Indian mobile number!`}},
    gender: {type: String, enum: ['Male', 'Female', 'Other']},
    ageGroup: {type: String},
    diabetesDuration: {type: String},
    medicines: {type: String},
    bloodSugars: {fasting: String, postMeal: String, notes: String},
    eatingHabits: {type: String},
    physicalActivity: {type: String},
    healthIssues: {type: String},
    otherHealthIssue: {type: String},
    isGenetic: {type: String},
    hasReport: {type: Boolean, default: false},
    reportFile: {type: String},
    reportFileName: {type: String},
    score: {type: Number, default: 0, min: 0, max: 30 },
    stage: { type: String, enum: ['Stage 1: Mild Sugar Level', 'Stage 2: Moderate Sugar Level', 'Stage 3: High Sugar Level']},
    monthsRequired: {type: String},
    monthsNum: {type: Number},
    controlPossibility: {type: Number},
    summary: {type: String},
    recommendationImage: {type: String},
    timeline: [{month: String, description: String}],
    nutritionPercent: {type: Number},
    lifestylePercent: {type: Number},
    weightPercent: {type: Number},
    nutritionImpact: {type: String},
    lifestyleImpact: {type: String},
    weightImpact: {type: String},
    allAnswers: { type: mongoose.Schema.Types.Mixed, default: {}},
    reportType: {type: String, enum: ['Blood Test', 'X-Ray', 'MRI', 'CT Scan', 'Urine Test', 'Other'], required: function () { return this.hasReport === true; }},
    doctorName: {type: String},
    status: {type: String, enum: ['Pending', 'Completed', 'Cancelled'],default: 'Pending'},    
    fileUrl: {type: String},
    fileName: {type: String},
    fileSize: {type: Number},
    fileType: {type: String},
    // diagnosisId: { type: mongoose.Schema.Types.ObjectId, ref: 'Diagnosis'      },
    createdAt: { type: Date, default: Date.now},
    updatedAt: {type: Date, default: Date.now}
})
module.exports = mongoose.model('Diagnosis', DiagnosisSchema);